# Overrides pour l'environnement PROD
# Merge avec consumption.yaml (base)

data: #fichier stocké en local stockage sur S3 non configurable
  raw_path: "../data/prod/raw_consumption.csv"
  train_path: "../data/prod/train_consumption.parquet"
  processed_path: "../data/prod/"

model:
  test_size: 0.2
  time_limit: 7200  # 2h max en prod

training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  time_limit: 7200

# MLflow prod
mlflow:
  experiment_name: "energy_consumption_prod"
  model_name: "consumption_model_prod"

# Monitoring plus strict en prod
monitoring:
  metric_target: 0.95  # Target 95%
  alert_threshold: 0.90  # Warning si < 90%
