name: 0 - Infra - Update HF Space Secrets

on:
  workflow_dispatch:

jobs:
  update_secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub python-dotenv requests
      
      - name: Update secrets in spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          MLFLOW_POSTGRES_URI: ${{ secrets.MLFLOW_POSTGRES_URI }}
          MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }}
          JUPYTER_TOKEN: ${{ secrets.JUPYTER_TOKEN }}
          N8N_DB_POSTGRES_URI: ${{ secrets.N8N_DB_POSTGRES_URI }}
          DB_TYPE: ${{ secrets.DB_TYPE }}
          DB_POSTGRESDB_USER: ${{ secrets.DB_POSTGRESDB_USER }}
          DB_POSTGRESDB_PASSWORD: ${{ secrets.DB_POSTGRESDB_PASSWORD }}
          DB_POSTGRESDB_HOST: ${{ secrets.DB_POSTGRESDB_HOST }}
          DB_POSTGRESDB_PORT: ${{ secrets.DB_POSTGRESDB_PORT }}
          DB_POSTGRESDB_DATABASE: ${{ secrets.DB_POSTGRESDB_DATABASE }}
          AIRFLOW_ADMIN_USER: ${{ secrets.AIRFLOW_ADMIN_USER }}
          AIRFLOW_ADMIN_PASSWORD: ${{ secrets.AIRFLOW_ADMIN_PASSWORD }} 
          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${{ secrets.AIRFLOW__DATABASE__SQL_ALCHEMY_CONN }}
          AIRFLOW__WEBSERVER__SECRET_KEY: ${{ secrets.AIRFLOW__WEBSERVER__SECRET_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ secrets.GH_REPO }}
          GH_BRANCH: ${{ secrets.GH_BRANCH }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
          AIRFLOW_HF_TOKEN: ${{ secrets.AIRFLOW_HF_TOKEN }}
          JINSUDAPI_HF_TOKEN: ${{ secrets.JINSUDAPI_HF_TOKEN }}
          EVIDENTLYUI_HF_TOKEN: ${{ secrets.EVIDENTLYUI_HF_TOKEN }}

        run: |
          python .github/scripts/hf_update_secrets.py
