name: 3 - Training - Consumption

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/3_run_training.yml'
      - 'pipelines/run_training.py'
      - 'src/ml/pipelines/training.py'
      - 'src/ml/config/**'
      - 'src/ml/utils/models/**'
      - 'src/ml/utils/data/**'
      - 'src/ml/utils/monitoring/**'
      - 'src/ml/utils/s3_handler.py'
      - 'data/templates/**'

jobs:
  training:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Run training pipeline
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT || (github.ref == 'refs/heads/main' && 'Prod' || 'Dev') }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'eu-west-3' }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET || 'data-store' }} #Not for Mlflow, but for storing the datasets
        run: |
          python pipelines/run_training.py
